### PR TITLE
Pull Request for TSE Review of Apple Landing Page Clone

### PR DESCRIPTION
**Pull request by Calvinoea**
Hello,

The pull request is being made for your review of the code for the Apple Landing Page clone before final submission. The Apple Landing Page clone task is part of the CSS curriculum which requires students to make a clone of an apple landing page. 

The page has a hero section, navigation bar, and a footer section. Users are able to read some information about Apple products on the page. Background gradients in CSS have been used to create the visual features of the navigation bar.

Please find below links to the live demo:

https://boring-neumann-0810f5.netlify.com/
https://rawcdn.githack.com/Calvinoea/Apple-Clone-Backgrounds-Gradients/tree/feature/index.html
https://raw.githack.com/Calvinoea/Apple-Clone-Backgrounds-Gradients/tree/feature/index.html

Thank you and best regards.

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @Calvinoea,
Your project looks good 👏👏, however, there are a few things that you need to fix.

**Bottom**
- The row that contains four elements that have images should be links (to another article or #).

**Additional Microverse Requirements (Pathwright)**
- Your stickler tests are failing, please fix these.
- Make sure your commits are descriptive, don't use general commits [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png)
- Please check HTML markup with this validator https://validator.w3.org/#validate_by_upload, you seem to be having some errors. [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png)
Screenshot from 2020-02-03 14-14-14
**Footer**

- Make sure your footer looks like the original one, the _contact us_  part should be to the right of _Job opportunities_.
screenshot

**[OPTIONAL]**
- I encourage you to use the `<main>` tag for the dominant content of the `<body>` of a document.

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes and request for another code review.
### Status: Changes Required.
_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

**Comment by Calvinoea** [comment]
> ### Kindly make the suggested changes and request for another code review.
> ### Status: Changes Required.
> _Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

Thank you for your feedback, @fatymahmed . I will make the changes as discussed.

**Comment by izaiasneto4** [comment]
### Hi @Calvinoea 👋 . Great job making the required changes.

Please, next time around try to make your commit messages more specific as said by @fatymahmed  🙏 . A thing that would solve your issue is to have a way to visualize stylelint in your IDE of choice... if that's vscode I would recommend [this tutorial](https://github.com/stylelint/vscode-stylelint). That would help you solve all of your CSS linting issues with just one commit 😄 

### Your project looks great 😎 . It's 👍  for me. You can submit the project completion for and merge. Have a great day!

TSE: Izaias Neto.

**Comment by Calvinoea** [comment]
> ### Hi @Calvinoea 👋 . Great job making the required changes.
> Please, next time around try to make your commit messages more specific as said by @fatymahmed 🙏 . A thing that would solve your issue is to have a way to visualize stylelint in your IDE of choice... if that's vscode I would recommend [this tutorial](https://github.com/stylelint/vscode-stylelint). That would help you solve all of your CSS linting issues with just one commit 😄
> 
> ### Your project looks great 😎 . It's 👍 for me. You can submit the project completion for and merge. Have a great day!
> TSE: Izaias Neto.

Thank you for your feedback, @izaiasneto4 . 😄 I will study the tutorial you provided.

**Pull request merged**
